kumuluzee:
  name: image-processing
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  config:
    etcd:
      hosts: http://etcd:2379
  health:
    checks:
      etcd-health-check:
        connection-url: http://etcd:2379/health
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                  <Configuration name="image-processing">
                    <Appenders>
                      <Console name="console" target="SYSTEM_OUT">
                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                      </Console>
                      <Socket name="logstash" host="127c4939-b207-4ae8-8499-977bff509d2c-ls.logit.io" port="11855"
                       protocol="tcp">
                        <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                      </Socket>
                    </Appenders>
                    <Loggers>
                      <Root level="all">
                        <AppenderRef ref="console" level="info"/>
                        <AppenderRef ref="logstash" level="trace"/>
                      </Root>
                    </Loggers>
                  </Configuration>'
  streaming:
    kafka:
      producer:
        bootstrap-servers: omnibus-01.srvs.cloudkafka.com:9094
        acks: all
        retries: 0
        batch-size: 16384
        linger-ms: 1
        buffer-memory: 33554432
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        security-protocol: SASL_SSL
        sasl-mechanism: SCRAM-SHA-256
        sasl-jaas-config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="ptjc95jg" password="<hidden>";'
      consumer:
        bootstrap-servers: omnibus-01.srvs.cloudkafka.com:9094
        group-id: ptjc95jg-consumer
        enable-auto-commit: true
        auto-commit-interval-ms: 1000
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        security-protocol: SASL_SSL
        sasl-mechanism: SCRAM-SHA-256
        sasl-jaas-config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="ptjc95jg" password="<hidden>";'
